"""initial migrate

Revision ID: f138d6cc732e
Revises:
Create Date: 2025-06-20 20:04:03.026346

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f138d6cc732e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("city",
    sa.Column("name", sa.String(length=30), nullable=False),
    sa.Column("additional_info", sa.String(length=255), nullable=True),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_index(op.f("ix_city_id"), "city", ["id"], unique=False)
    op.create_table("temperature",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("city_id", sa.Integer(), nullable=False),
    sa.Column("date_time", sa.DateTime(), nullable=False),
    sa.Column("temperature", sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(["city_id"], ["city.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperature")
    op.drop_index(op.f("ix_city_id"), table_name="city")
    op.drop_table("city")
    # ### end Alembic commands ###
